# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7101e6e
_src_path: https://gitlab.com/gemseo/dev/copier-gemseo
author_email: ian.costa-alves.external@irt-saintexupery.com
author_name: Ian COSTA ALVES
gemseo_min_version: '6'
package_is_a_gemseo_plugin: true
project_is_open_source: true
project_name: numerical-optimization-of-aviation-decarbonization-scenarios
project_name_suffix: core
project_slug: core
short_description: Numerical Optimization of Aviation Decarbonization Scenarios with
    GEMSEO-JAX
use_gemseo_develop: false
